/*
 * This file is generated by jOOQ.
 */
package com.jooq.crud.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Article implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  title;
    private String  description;
    private Integer authorId;

    public Article() {}

    public Article(Article value) {
        this.id = value.id;
        this.title = value.title;
        this.description = value.description;
        this.authorId = value.authorId;
    }

    public Article(
        Integer id,
        String  title,
        String  description,
        Integer authorId
    ) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.authorId = authorId;
    }

    /**
     * Getter for <code>mydb.ARTICLE.ID</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>mydb.ARTICLE.ID</code>.
     */
    public Article setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>mydb.ARTICLE.TITLE</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>mydb.ARTICLE.TITLE</code>.
     */
    public Article setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>mydb.ARTICLE.DESCRIPTION</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>mydb.ARTICLE.DESCRIPTION</code>.
     */
    public Article setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>mydb.ARTICLE.AUTHOR_ID</code>.
     */
    public Integer getAuthorId() {
        return this.authorId;
    }

    /**
     * Setter for <code>mydb.ARTICLE.AUTHOR_ID</code>.
     */
    public Article setAuthorId(Integer authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Article other = (Article) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (title == null) {
            if (other.title != null)
                return false;
        }
        else if (!title.equals(other.title))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (authorId == null) {
            if (other.authorId != null)
                return false;
        }
        else if (!authorId.equals(other.authorId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.authorId == null) ? 0 : this.authorId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Article (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(authorId);

        sb.append(")");
        return sb.toString();
    }
}
