/*
 * This file is generated by jOOQ.
 */
package com.jooq.crud.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  firstName;
    private String  lastName;
    private Integer age;

    public Author() {}

    public Author(Author value) {
        this.id = value.id;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.age = value.age;
    }

    public Author(
        Integer id,
        String  firstName,
        String  lastName,
        Integer age
    ) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
    }

    /**
     * Getter for <code>mydb.AUTHOR.ID</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>mydb.AUTHOR.ID</code>.
     */
    public Author setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>mydb.AUTHOR.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>mydb.AUTHOR.FIRST_NAME</code>.
     */
    public Author setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>mydb.AUTHOR.LAST_NAME</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>mydb.AUTHOR.LAST_NAME</code>.
     */
    public Author setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Getter for <code>mydb.AUTHOR.AGE</code>.
     */
    public Integer getAge() {
        return this.age;
    }

    /**
     * Setter for <code>mydb.AUTHOR.AGE</code>.
     */
    public Author setAge(Integer age) {
        this.age = age;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Author other = (Author) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!firstName.equals(other.firstName))
            return false;
        if (lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!lastName.equals(other.lastName))
            return false;
        if (age == null) {
            if (other.age != null)
                return false;
        }
        else if (!age.equals(other.age))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.age == null) ? 0 : this.age.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Author (");

        sb.append(id);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(age);

        sb.append(")");
        return sb.toString();
    }
}
