/*
 * This file is generated by jOOQ.
 */
package com.jooq.crud.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HibernateSequence implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long nextVal;

    public HibernateSequence() {}

    public HibernateSequence(HibernateSequence value) {
        this.nextVal = value.nextVal;
    }

    public HibernateSequence(
        Long nextVal
    ) {
        this.nextVal = nextVal;
    }

    /**
     * Getter for <code>mydb.hibernate_sequence.next_val</code>.
     */
    public Long getNextVal() {
        return this.nextVal;
    }

    /**
     * Setter for <code>mydb.hibernate_sequence.next_val</code>.
     */
    public HibernateSequence setNextVal(Long nextVal) {
        this.nextVal = nextVal;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final HibernateSequence other = (HibernateSequence) obj;
        if (nextVal == null) {
            if (other.nextVal != null)
                return false;
        }
        else if (!nextVal.equals(other.nextVal))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.nextVal == null) ? 0 : this.nextVal.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HibernateSequence (");

        sb.append(nextVal);

        sb.append(")");
        return sb.toString();
    }
}
