/*
 * This file is generated by jOOQ.
 */
package com.jooq.crud.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductTbl implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;
    private Double  price;
    private Integer quantity;

    public ProductTbl() {}

    public ProductTbl(ProductTbl value) {
        this.id = value.id;
        this.name = value.name;
        this.price = value.price;
        this.quantity = value.quantity;
    }

    public ProductTbl(
        Integer id,
        String  name,
        Double  price,
        Integer quantity
    ) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.quantity = quantity;
    }

    /**
     * Getter for <code>mydb.product_tbl.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>mydb.product_tbl.id</code>.
     */
    public ProductTbl setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>mydb.product_tbl.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>mydb.product_tbl.name</code>.
     */
    public ProductTbl setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>mydb.product_tbl.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>mydb.product_tbl.price</code>.
     */
    public ProductTbl setPrice(Double price) {
        this.price = price;
        return this;
    }

    /**
     * Getter for <code>mydb.product_tbl.quantity</code>.
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>mydb.product_tbl.quantity</code>.
     */
    public ProductTbl setQuantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProductTbl other = (ProductTbl) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (price == null) {
            if (other.price != null)
                return false;
        }
        else if (!price.equals(other.price))
            return false;
        if (quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!quantity.equals(other.quantity))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductTbl (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(price);
        sb.append(", ").append(quantity);

        sb.append(")");
        return sb.toString();
    }
}
