/*
 * This file is generated by jOOQ.
 */
package com.jooq.crud.model;


import com.jooq.crud.model.tables.Article;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in mydb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ARTICLE_AUTHER_ID_IDX = Internal.createIndex(DSL.name("AUTHER_ID_idx"), Article.ARTICLE, new OrderField[] { Article.ARTICLE.AUTHOR_ID }, false);
}
