/*
 * This file is generated by jOOQ.
 */
package com.jooq.crud.model;


import com.jooq.crud.model.tables.Article;
import com.jooq.crud.model.tables.Author;
import com.jooq.crud.model.tables.Book;
import com.jooq.crud.model.tables.EmployeeTbl;
import com.jooq.crud.model.tables.HibernateSequence;
import com.jooq.crud.model.tables.PersonTbl;
import com.jooq.crud.model.tables.ProductTbl;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mydb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mydb</code>
     */
    public static final Mydb MYDB = new Mydb();

    /**
     * The table <code>mydb.ARTICLE</code>.
     */
    public final Article ARTICLE = Article.ARTICLE;

    /**
     * The table <code>mydb.AUTHOR</code>.
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>mydb.book</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * The table <code>mydb.employee_tbl</code>.
     */
    public final EmployeeTbl EMPLOYEE_TBL = EmployeeTbl.EMPLOYEE_TBL;

    /**
     * The table <code>mydb.hibernate_sequence</code>.
     */
    public final HibernateSequence HIBERNATE_SEQUENCE = HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * The table <code>mydb.person_tbl</code>.
     */
    public final PersonTbl PERSON_TBL = PersonTbl.PERSON_TBL;

    /**
     * The table <code>mydb.product_tbl</code>.
     */
    public final ProductTbl PRODUCT_TBL = ProductTbl.PRODUCT_TBL;

    /**
     * No further instances allowed
     */
    private Mydb() {
        super("mydb", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Article.ARTICLE,
            Author.AUTHOR,
            Book.BOOK,
            EmployeeTbl.EMPLOYEE_TBL,
            HibernateSequence.HIBERNATE_SEQUENCE,
            PersonTbl.PERSON_TBL,
            ProductTbl.PRODUCT_TBL);
    }
}
