/*
 * This file is generated by jOOQ.
 */
package com.jooq.crud.model;


import com.jooq.crud.model.tables.Article;
import com.jooq.crud.model.tables.Author;
import com.jooq.crud.model.tables.Book;
import com.jooq.crud.model.tables.EmployeeTbl;
import com.jooq.crud.model.tables.HibernateSequence;
import com.jooq.crud.model.tables.PersonTbl;
import com.jooq.crud.model.tables.ProductTbl;


/**
 * Convenience access to all tables in mydb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mydb.ARTICLE</code>.
     */
    public static final Article ARTICLE = Article.ARTICLE;

    /**
     * The table <code>mydb.AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>mydb.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>mydb.employee_tbl</code>.
     */
    public static final EmployeeTbl EMPLOYEE_TBL = EmployeeTbl.EMPLOYEE_TBL;

    /**
     * The table <code>mydb.hibernate_sequence</code>.
     */
    public static final HibernateSequence HIBERNATE_SEQUENCE = HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * The table <code>mydb.person_tbl</code>.
     */
    public static final PersonTbl PERSON_TBL = PersonTbl.PERSON_TBL;

    /**
     * The table <code>mydb.product_tbl</code>.
     */
    public static final ProductTbl PRODUCT_TBL = ProductTbl.PRODUCT_TBL;
}
