/*
 * This file is generated by jOOQ.
 */
package com.jooq.crud.model.tables;


import com.jooq.crud.model.Mydb;
import com.jooq.crud.model.tables.records.HibernateSequenceRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HibernateSequence extends TableImpl<HibernateSequenceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mydb.hibernate_sequence</code>
     */
    public static final HibernateSequence HIBERNATE_SEQUENCE = new HibernateSequence();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HibernateSequenceRecord> getRecordType() {
        return HibernateSequenceRecord.class;
    }

    /**
     * The column <code>mydb.hibernate_sequence.next_val</code>.
     */
    public final TableField<HibernateSequenceRecord, Long> NEXT_VAL = createField(DSL.name("next_val"), SQLDataType.BIGINT, this, "");

    private HibernateSequence(Name alias, Table<HibernateSequenceRecord> aliased) {
        this(alias, aliased, null);
    }

    private HibernateSequence(Name alias, Table<HibernateSequenceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>mydb.hibernate_sequence</code> table reference
     */
    public HibernateSequence(String alias) {
        this(DSL.name(alias), HIBERNATE_SEQUENCE);
    }

    /**
     * Create an aliased <code>mydb.hibernate_sequence</code> table reference
     */
    public HibernateSequence(Name alias) {
        this(alias, HIBERNATE_SEQUENCE);
    }

    /**
     * Create a <code>mydb.hibernate_sequence</code> table reference
     */
    public HibernateSequence() {
        this(DSL.name("hibernate_sequence"), null);
    }

    public <O extends Record> HibernateSequence(Table<O> child, ForeignKey<O, HibernateSequenceRecord> key) {
        super(child, key, HIBERNATE_SEQUENCE);
    }

    @Override
    public Schema getSchema() {
        return Mydb.MYDB;
    }

    @Override
    public HibernateSequence as(String alias) {
        return new HibernateSequence(DSL.name(alias), this);
    }

    @Override
    public HibernateSequence as(Name alias) {
        return new HibernateSequence(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HibernateSequence rename(String name) {
        return new HibernateSequence(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HibernateSequence rename(Name name) {
        return new HibernateSequence(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
