/*
 * This file is generated by jOOQ.
 */
package com.jooq.crud.model.tables.records;


import com.jooq.crud.model.tables.PersonTbl;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonTblRecord extends UpdatableRecordImpl<PersonTblRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mydb.person_tbl.id</code>.
     */
    public PersonTblRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>mydb.person_tbl.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mydb.person_tbl.name</code>.
     */
    public PersonTblRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>mydb.person_tbl.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PersonTbl.PERSON_TBL.ID;
    }

    @Override
    public Field<String> field2() {
        return PersonTbl.PERSON_TBL.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public PersonTblRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PersonTblRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PersonTblRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonTblRecord
     */
    public PersonTblRecord() {
        super(PersonTbl.PERSON_TBL);
    }

    /**
     * Create a detached, initialised PersonTblRecord
     */
    public PersonTblRecord(Integer id, String name) {
        super(PersonTbl.PERSON_TBL);

        setId(id);
        setName(name);
    }
}
